name: pangeo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aiohttp=3.7.2=py38h1e0a361_0
  - argon2-cffi=20.1.0=py38h1e0a361_2
  - asciitree=0.3.3=py_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - bokeh=2.2.3=py38h32f6830_0
  - boost-cpp=1.74.0=h9359b55_0
  - bottleneck=1.3.2=py38hab2c0dc_2
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h9f066cc_1006
  - cartopy=0.18.0=py38hed7a9dc_1
  - certifi=2020.6.20=py38h924ce5b_2
  - cffi=1.14.3=py38h1bdcb99_1
  - cfitsio=3.470=hce51eda_7
  - cftime=1.2.1=py38h8790de6_0
  - chardet=3.0.4=py38h924ce5b_1008
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.0=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.2.1=py38h7699a38_0
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h1e0a361_1
  - dask=2.27.0=py_0
  - dask-core=2.27.0=py_0
  - dask-jobqueue=0.7.1=py_0
  - dask-labextension=2.0.2=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.27.0=py38h32f6830_0
  - docrep=0.3.1=pyh9f0ad1d_0
  - entrypoints=0.3=py38h32f6830_1002
  - esmf=8.0.1=mpi_mpich_h213fab7_101
  - esmpy=8.0.1=mpi_mpich_py38h08b7006_100
  - expat=2.2.9=he1b5a44_2
  - fasteners=0.14.1=py_3
  - ffmpeg=4.3.1=h167e202_0
  - fiona=1.8.17=py38h676c6b2_1
  - fontconfig=2.13.1=h7e3eb15_1002
  - freetype=2.10.4=h7ca028e_0
  - freexl=1.0.5=h516909a_1002
  - fsspec=0.8.4=py_0
  - future=0.18.2=py38h32f6830_2
  - gdal=3.1.4=py38h9edfc58_0
  - geopandas=0.8.1=py_0
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h5d11630_3
  - gettext=0.19.8.1=hf34092f_1004
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.66.2=h58526e2_0
  - gmp=6.2.0=h58526e2_4
  - gnutls=3.6.13=h79a8f9a_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=mpi_mpich_h58e33ef_1010
  - heapdict=1.0.1=py_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=5.3.4=py38h1cdfbd6_1
  - ipython=7.19.0=py38h81c977d_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py38_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.13.1=hbfbb72e_1002
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter-server-proxy=1.5.0=py_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38h32f6830_2
  - jupyterlab=2.2.2=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - jupytext=1.5.2=pyh9f0ad1d_0
  - kealib=1.4.13=h33137a7_1
  - kiwisolver=1.3.1=py38h82cb98a_0
  - krb5=1.17.1=hfafb76e_3
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgdal=3.1.4=h670eac6_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglib=2.66.2=hbe7bbb4_0
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h74f7ee3_1012
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=mpi_mpich_h2f92d0d_6
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h5513abc_2
  - libsodium=1.0.18=h516909a_1
  - libspatialindex=1.9.3=he1b5a44_3
  - libspatialite=5.0.0=h4dde289_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=h4f3a223_6
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.38.0=h516909a_0
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - llvmlite=0.34.0=py38h4f45e52_2
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py38h8df0ef7_2
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py38h91b0d89_1
  - mistune=0.8.4=py38h1e0a361_1002
  - monotonic=1.5=py_0
  - more-itertools=8.6.0=pyhd8ed1ab_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py38h4a80816_2
  - mpich=3.3.2=hc856adb_3
  - msgpack-python=1.0.0=py38hbf85e49_2
  - multidict=4.7.5=py38h1e0a361_2
  - munch=2.5.0=py_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38h32f6830_2
  - nbformat=5.0.8=py_0
  - nbserverproxy=0.8.8=py_1000
  - nc-time-axis=1.2.0=py_1
  - ncurses=6.2=he1b5a44_2
  - nest-asyncio=1.4.2=pyhd8ed1ab_0
  - netcdf-fortran=4.5.3=mpi_mpich_h3923e1a_1
  - netcdf4=1.5.4=nompi_py38hec8b9af_103
  - nettle=3.4.1=h1bed415_1002
  - nodejs=14.7.0=h568c755_0
  - notebook=6.1.4=py38h32f6830_1
  - numba=0.51.2=py38hc5bc63f_0
  - numcodecs=0.7.2=py38h950e882_1
  - numpy=1.19.1=py38h8854b6b_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h8b12597_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1h=h516909a_0
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.0=py38h950e882_0
  - pandoc=2.11.0.4=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.0=py_1
  - partd=1.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py38h9776b28_0
  - pip=20.2.4=py_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=0.13.1=py38h924ce5b_3
  - poppler=0.89.0=h4190859_1
  - poppler-data=0.4.10=0
  - postgresql=12.3=h8573dbc_2
  - proj=7.1.1=h966b41f_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - properscoring=0.1=py_0
  - psutil=5.7.3=py38h8df0ef7_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyepsg=0.4.0=py_0
  - pygments=2.7.2=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38h56787f0_3
  - pyrsistent=0.17.3=py38h1e0a361_1
  - pyshp=2.1.2=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h924ce5b_2
  - pyspharm=1.0.9=py38h522b421_1005
  - pytest=6.0.1=py38h32f6830_0
  - python=3.8.6=h852b56e_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pyyaml=5.3.1=py38h8df0ef7_1
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.0=he28a2e2_2
  - regionmask=0.4.0=py_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rtree=0.9.4=py38h08f867b_1
  - scikit-learn=0.23.2=py38h5d63f67_2
  - scipy=1.5.2=py38h8c5af15_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h924ce5b_2
  - shapely=1.7.1=py38hc7361b7_1
  - simpervisor=0.3=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_1
  - tblib=1.6.0=py_0
  - terminado=0.9.1=py38h32f6830_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tiledb=2.1.2=h47b529c_0
  - tk=8.6.10=hed695b0_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h25fe258_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzcode=2020a=h516909a_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38h32f6830_1
  - windspharm=1.7.0=py38h32f6830_1002
  - x264=1!152.20180806=h14c3975_0
  - xarray=0.16.1=py_0
  - xerces-c=3.2.3=hfe33f54_1
  - xesmf=0.3.0=py_0
  - xhistogram=0.1.1=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xrft=0.2.0=py_0
  - xskillscore=0.0.18=py_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.2=py38h1e0a361_0
  - zarr=2.4.0=py_0
  - zeromq=4.3.3=he1b5a44_2
  - zict=2.0.0=py_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h6597ccf_2
prefix: /g/data/v14/ds0092/software/miniconda3/envs/pangeo
